In [1]:
#Importing Packages
from pyspark import SparkContext
from pyspark.sql import SparkSession,SQLContext
from pyspark.sql.functions import udf,col,lower,upper
from pyspark.sql.types import StringType

In [2]:
#Creating a udf
f=lambda a: 'Not Exists' if(a==1) else 'Exists'
sparf_udf=udf(f,StringType())

In [3]:
# Reading the Aadhar Data using SQLContext
aadhar_df=spark.read.format('csv').option('sep',',').option('header',True).option('inferSchema',True).load('/FileStore/tables/UIDAI_ENR_DETAIL_20170308-034f9.csv')

In [4]:
#Basic Analysis
len(aadhar_df.columns) 
# It contains 12 Columns
aadhar_df.count()
#  It Contains round 470035 Rows
aadhar_df.printSchema()
'''
 |-- Registrar: string (nullable = true)
 |-- Enrolment Agency: string (nullable = true)
 |-- State: string (nullable = true)
 |-- District: string (nullable = true)
 |-- Sub District: string (nullable = true)
 |-- Pin Code: string (nullable = true)
 |-- Gender: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- Aadhaar generated: integer (nullable = true)
 |-- Enrolment Rejected: integer (nullable = true)
 |-- Residents providing email: integer (nullable = true)
 |-- Residents providing mobile number: integer (nullable = true)
'''
# To Describe the Data
aadhar_df.describe().show()

In [5]:
# Select the distinct state and district
aadhar_df.select('State','District').distinct().show()
aadhar_df.select('Residents providing mobile number').distinct().show()
aadhar_df.select('Gender','Age').distinct().show()

# Distinct values 
aadhar_df.select('Aadhaar generated','Enrolment Rejected','Residents providing email').distinct().show()

In [6]:
# Cross Tab between Age Gender
aadhar_df.crosstab('Age','Gender').show()

In [7]:
# Remove Duplicates
print(aadhar_df.count())
aadhar_df=aadhar_df.dropDuplicates()
# TOtally 9 duplicate records are present
print(aadhar_df.count())
# TOtally 2records are presnt which has more number of NA's
aadhar_df=aadhar_df.dropna(thresh=11)
print(aadhar_df.count())

In [8]:
# To Find the ratio of Number of Boys to Girls
df=aadhar_df.groupBy(['State','District','Gender']).agg({'*':'count'}).selectExpr('State','District','Gender','`count(1)` as Count').sort('Count',ascending=False)
df.createOrReplaceTempView('aadhar_district_tbl')
sqlContext.sql("select State,District,MaleCount,FemaleCount,MaleCount/FemaleCount as CountRatio from (select State,District,sum(case when Gender='M' then Count else 0 end) as MaleCount ,sum(case when Gender='F' then Count else 0 end) as FemaleCount  from aadhar_district_tbl group by State,District)tmp where MaleCount/FemaleCount != 0 and MaleCount/FemaleCount is not null order by CountRatio ").show(30)